export const pixelArtItems = [
  {
    src: "/pixel-deco/diamond.png",
    alt: "Diamond pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/bubble-heart.png",
    alt: "Bubble heart pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/plus.png",
    alt: "Plus pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/notification.png",
    alt: "Notification pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/pixel.png",
    alt: "Pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/speech-bubble-heart.png",
    alt: "Speech bubble heart pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/lightbulb.png",
    alt: "Lightbulb pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/ghost.png",
    alt: "Ghost pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/bridge.png",
    alt: "Bridge pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/lightbulb-insight.png",
    alt: "Lightbulb insight pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-deco/lightbulb-learning.png",
    alt: "Lightbulb learning pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  // Additional pixel art items
  {
    src: "/pixel-art-game-controller.png",
    alt: "Game controller pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-art-character.png",
    alt: "Character pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-art-landscape.png",
    alt: "Landscape pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-art-spaceship.png",
    alt: "Spaceship pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
  {
    src: "/pixel-art-tree.png",
    alt: "Tree pixel art",
    width: 128,
    height: 128,
    thumbnailWidth: 64,
    thumbnailHeight: 64,
  },
]
